package com.easymd.ui.theme

import androidx.compose.ui.graphics.Color

// ── Material You seed color ───────────────────────────────────────────────
val Seed = Color(0xFF1A73E8)

// ── Light scheme ─────────────────────────────────────────────────────────
val md_light_primary             = Color(0xFF1A73E8)
val md_light_onPrimary           = Color(0xFFFFFFFF)
val md_light_primaryContainer    = Color(0xFFD3E3FD)
val md_light_onPrimaryContainer  = Color(0xFF001D35)
val md_light_secondary           = Color(0xFF5B738B)
val md_light_onSecondary         = Color(0xFFFFFFFF)
val md_light_secondaryContainer  = Color(0xFFD6E4F7)
val md_light_onSecondaryContainer= Color(0xFF141F29)
val md_light_tertiary            = Color(0xFF715573)
val md_light_onTertiary          = Color(0xFFFFFFFF)
val md_light_tertiaryContainer   = Color(0xFFFBD7FA)
val md_light_onTertiaryContainer = Color(0xFF29102C)
val md_light_error               = Color(0xFFB3261E)
val md_light_onError             = Color(0xFFFFFFFF)
val md_light_errorContainer      = Color(0xFFF9DEDC)
val md_light_onErrorContainer    = Color(0xFF410E0B)
val md_light_background          = Color(0xFFF8F9FF)
val md_light_onBackground        = Color(0xFF191C20)
val md_light_surface             = Color(0xFFF8F9FF)
val md_light_onSurface           = Color(0xFF191C20)
val md_light_surfaceVariant      = Color(0xFFDDE3EA)
val md_light_onSurfaceVariant    = Color(0xFF41484D)
val md_light_outline             = Color(0xFF71787E)
val md_light_outlineVariant      = Color(0xFFC1C7CE)
val md_light_inverseSurface      = Color(0xFF2E3135)
val md_light_inverseOnSurface    = Color(0xFFEFF0F4)

// ── Dark scheme ──────────────────────────────────────────────────────────
val md_dark_primary              = Color(0xFF9ECBFF)
val md_dark_onPrimary            = Color(0xFF003353)
val md_dark_primaryContainer     = Color(0xFF004A75)
val md_dark_onPrimaryContainer   = Color(0xFFD3E3FD)
val md_dark_secondary            = Color(0xFFBAC8D9)
val md_dark_onSecondary          = Color(0xFF253240)
val md_dark_secondaryContainer   = Color(0xFF3D4B5A)
val md_dark_onSecondaryContainer = Color(0xFFD6E4F7)
val md_dark_tertiary             = Color(0xFFDEB8DF)
val md_dark_onTertiary           = Color(0xFF3F2841)
val md_dark_tertiaryContainer    = Color(0xFF573D59)
val md_dark_onTertiaryContainer  = Color(0xFFFBD7FA)
val md_dark_error                = Color(0xFFF2B8B5)
val md_dark_onError              = Color(0xFF601410)
val md_dark_errorContainer       = Color(0xFF8C1D18)
val md_dark_onErrorContainer     = Color(0xFFF9DEDC)
val md_dark_background           = Color(0xFF111418)
val md_dark_onBackground         = Color(0xFFE2E2E6)
val md_dark_surface              = Color(0xFF111418)
val md_dark_onSurface            = Color(0xFFE2E2E6)
val md_dark_surfaceVariant       = Color(0xFF41484D)
val md_dark_onSurfaceVariant     = Color(0xFFC1C7CE)
val md_dark_outline              = Color(0xFF8B9197)
val md_dark_outlineVariant       = Color(0xFF41484D)
val md_dark_inverseSurface       = Color(0xFFE2E2E6)
val md_dark_inverseOnSurface     = Color(0xFF2E3135)

// ── Syntax highlight palette ─────────────────────────────────────────────
val SyntaxHeadingLight    = Color(0xFF1A73E8)
val SyntaxHeadingDark     = Color(0xFF74B5FF)
val SyntaxCodeLight       = Color(0xFFC62828)
val SyntaxCodeDark        = Color(0xFFF28B82)
val SyntaxCodeBgLight     = Color(0xFFE4E9F4)
val SyntaxCodeBgDark      = Color(0xFF1E2330)
val SyntaxQuoteLight      = Color(0xFF1A73E8)
val SyntaxQuoteDark       = Color(0xFF9ECBFF)
val SyntaxLinkLight       = Color(0xFF1A73E8)
val SyntaxLinkDark        = Color(0xFF9ECBFF)
val SyntaxMarkerLight     = Color(0xFF71787E)
val SyntaxMarkerDark      = Color(0xFF8B9197)
val SyntaxItalicLight     = Color(0xFF715573)
val SyntaxItalicDark      = Color(0xFFDEB8DF)
